language: python
python:
  - "2.7"
install:
  - pip install -e .
  - pip install pep8 pyflakes nose
# command to run tests
script:
  - pep8 --config=./pep8rc .
# - pyflakes .
# - nosetests --with-doctest
